




INSERT INTO COUNTRY(ID,NAME,AGE,ADDRESS,SALARY)
VALUES('1','오상훈',18,'부천시 심곡동',100)
;
INSERT INTO COUNTRY(ID,NAME,AGE,ADDRESS,SALARY)
VALUES('1','오상훈',18,'부천시 심곡동',100)
;
INSERT INTO COUNTRY(ID,NAME,AGE,ADDRESS,SALARY)
VALUES('4','오상훈',35,'서울 심곡동',200)
;

